export const SET_USER_INFO_RESULT = 'SET_USER_INFO_RESULT';
export const SET_USER_INFO_REQUEST = 'SET_USER_INFO_REQUEST';
export const ADD_TO_REPOS_LIST = 'ADD_TO_REPOS_LIST';
export const ADD_TO_REPOS_LIST_REQUEST = 'ADD_TO_REPOS_LIST_REQUEST';
